### ISSUE TITLE
SwipeHorizontalMenuLayout fractions cause crash in other languages

### ISSUE THREAD

**Issue by mthormann-dhi** [TUBB/SwipeMenuRecyclerView#14]
The line 204 below in SwipeHorizontalMenuLayout is crashing the library with a NumberFormatException when the language on the phone supports a decimal format with "," or other character (German for example).  

**fraction = Float.parseFloat(mDecimalFormat.format(fraction));**

Fatal Exception: java.lang.NumberFormatException: Invalid float: ",14"
       at java.lang.StringToReal.invalidReal(StringToReal.java:63)
       at java.lang.StringToReal.initialParse(StringToReal.java:164)
       at java.lang.StringToReal.parseFloat(StringToReal.java:323)
       at java.lang.Float.parseFloat(Float.java:306)
       at com.tubb.smrv.SwipeHorizontalMenuLayout.scrollTo(SwipeHorizontalMenuLayout.java:204)
       at android.view.View.scrollBy(View.java:12526)
       at com.tubb.smrv.SwipeHorizontalMenuLayout.onTouchEvent(SwipeHorizontalMenuLayout.java:102)
💯

**Comment by TUBB** [comment]
I use the default `Locale`. I will  change to `Locale.ENGLISH`

**Comment by mthormann-dhi** [comment]
Thanks for the quick response!    I worked around temporarily by subclassing SwipeMenuHorizontalLayout and setting the locale in the constructors.     

```
    mDecimalFormat = DecimalFormat.getNumberInstance(Locale.US);
```

Glad you made the property protected :)
