### ISSUE TITLE
viewHolder.sml.smoothCloseMenu();这个方法有个问题，从后往前删没问题，如果从第一个开始删执行这个关闭方法就报下面BUG

### ISSUE THREAD

**Issue by xiedong** [TUBB/SwipeMenuRecyclerView#27]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tubb.smrv.b.d.b(android.widget.OverScroller, int, int)' on a null object reference
                                                           at com.tubb.smrv.SwipeHorizontalMenuLayout.b(SwipeHorizontalMenuLayout.java:275)
                                                           at com.tubb.smrv.SwipeMenuLayout.j(SwipeMenuLayout.java:108)
                                                           at com.android.lft.block.main.message.view.MessageCenterAdapter.a(MessageCenterAdapter.java:132)
                                                           at com.android.lft.block.main.message.view.MessageCenterListActivity.b(MessageCenterListActivity.java:220)
                                                           at com.android.lft.block.main.message.a.k.a(MessageStatusUpdatePresenterImpl.java:42)
                                                           at com.android.lft.block.common.a.l.a(ModelInterfaceImpl.java:145)
                                                           at com.android.lft.block.common.a.l.call(ModelInterfaceImpl.java:77)
                                                           at rx.ce.onNext(Observable.java:8192)
                                                           at rx.c.f.onNext(SafeSubscriber.java:139)
                                                           at rx.internal.operators.fa$a.call(OperatorObserveOn.java:207)
                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                           at android.os.Looper.loop(Looper.java:148)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by xiedong** [comment]
作者，我按照你DEMO的方式调取的
      final ViewHolder finalViewHolder = viewHolder;
            viewHolder.btDelete.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    // must close normal
                    finalViewHolder.sml.smoothCloseMenu();
                    users.remove(position);
                    notifyDataSetChanged();
                }
            });
如果删除的是LISTVIEW 第一个 必出这个BUG
是调这个   finalViewHolder.sml.smoothCloseMenu();方法出现的 报mCurrentSwiper空指针

**Comment by xiedong** [comment]
用的是这个类SimpleLvActivity

**Comment by thiru-wta** [comment]
Hello, 
I used your library. I have a problem with the library.
When we swipe left or right, the item name should not move right or left. What changes I have to do to get the required output.

**Comment by TUBB** [comment]
@thiru-wta Sorry, it's not support this.

**Comment by TUBB** [comment]
@xiedong 不好意思哈，这几个月比较忙，都没维护这个库。这个问题我争取晚上解决💪

**Comment by xiedong** [comment]
没事了作者，这个问题我发现是我使用错误，把那个对象用在了 监听外部导致了异步错误，我改过来了，可以了

**Comment by TUBB** [comment]
@xiedong 👌
